CONTRIBUTORS.md, README.md, Rakefile, data/common.yaml, manifests/base.pp, manifests/component/action.pp, manifests/component/custom_config.pp, manifests/component/global_config.pp, manifests/component/input.pp, manifests/component/template.pp, manifests/config/actions.pp, manifests/config/custom.pp, manifests/config/global.pp, manifests/config/inputs.pp, manifests/config/main_queue.pp, manifests/config/modules.pp, manifests/config/templates.pp
- Fixed the variable scoping styling in *.pp files
- Updated Rakefile for epp validation
- Updated readme for typo
- Removed #rsyslog::client::templates option from example data/common.yaml as templates option not declared in client.pp
=> fixed the variable scoping styling and updated rake file for epp validation

README.md
fixed variable typo in the Readme as per the discussion.
=> fixed the variable typo in readme

Rakefile, spec/classes/config/main_queue_spec.rb, spec/defines/component/legacy_config_spec.rb
The main_queue_priority is reassigned as part of the pull request https://github.com/crayfishx/puppet-rsyslog/pull/6 This test is failing as part of the old data which is in the master. once the pull request 6 is accepted this test should start passing.
=> Feature/ Added more tests for the legacy_config / main_queue class.

manifests/config/global.pp, spec/defines/component/global_config_spec.rb, templates/global_config.epp
```
rsyslog::server::global_config:
umask:
value: '0000'
type: legacy
priority: 01
RepeatedMsgReduction:
value: 'on'
type: legacy
PrivDropToUser:
value: 'syslog'
type: legacy
PrivDropToGroup:
value: 'syslog'
type: legacy
parser.escapeControlCharactersOnReceive:
value: 'on'
workDirectory:
value: '/var/spool/rsyslog'
maxMessageSize:
value: '64k'
```
will produce
```
$umask 0000
$PrivDropToGroup syslog
$PrivDropToUser syslog
$RepeatedMsgReduction on
global (
parser.escapeControlCharactersOnReceive="on"
workDirectory="/var/spool/rsyslog"
maxMessageSize="64k"
)
```
=> fixed the global params config styling

README.md
Documentation updated for the following changes:
*  global priorities updated
*  modules component to support the optional parameters
* action component to support the optional facility type.
=> Updated the documentaion for the new changes in action / module

README.md, data/common.yaml, manifests/component/parser.pp, manifests/config.pp, manifests/config/parsers.pp, manifests/init.pp, manifests/server.pp, spec/defines/component/input_spec.rb, spec/defines/component/parser_spec.rb, templates/parser.epp
=> Add support for Parser config object

README.md, manifests/component/lookup_table.pp, spec/defines/component/ruleset_spec.rb, templates/ruleset.epp
=> Add basic support for rsyslog filters in rulesets

metadata.json
=> bump lowest puppet version 4.4.0->4.10.9

README.md
=> Updated docs to correctly reflect the priority functionality

spec/defines/component/property_filter_spec.rb, types/propertyoperator.pp
=> Remove invalid property filter operators

templates/tasks.epp
=> #59 Fix action facility bug

README.md, spec/acceptance/ruleset_spec.rb, spec/defines/component/ruleset_spec.rb, templates/ruleset.epp
=> Remove unique name requirement for Filters inside of a Ruleset resource

.fixtures.yml
=> use gitrepos in .fixtures.yml

.fixtures.yml, .github/CONTRIBUTING.md, .msync.yml, .sync.yml, .travis.yml, Gemfile, spec/classes/coverage_spec.rb, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 2.2.0

README.md
=> #112 Fix ruleset expression filter examples

spec/type_aliases/actions/outputs/omrelp_spec.rb, types/actions/outputs/omrelp.pp, types/modules/input.pp
Just fixing a couple of omissions that I noticed.
=> types updates

.github/CONTRIBUTING.md, .msync.yml, Gemfile, manifests/base.pp, manifests/config/actions.pp, manifests/config/custom.pp, manifests/config/expression_filters.pp, manifests/config/global.pp, manifests/config/inputs.pp, manifests/config/legacy.pp, manifests/config/lookup_tables.pp, manifests/config/main_queue.pp, manifests/config/modules.pp, manifests/config/parsers.pp, manifests/config/property_filters.pp, manifests/config/rulesets.pp, manifests/config/templates.pp, manifests/generate_concat.pp, spec/spec_helper.rb
=> modulesync 2.8.0

README.md
Just fix the typo in README.md conditionals example
=> Fix typo in conditionals example

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 5.1.0

README.md, metadata.json
=> Update README with more Puppet DSL examples

manifests/base.pp
Make the way we define conditional dependencies consistent and remove
the, (IMO dubious), use of merging multiple parameters into the splat
attribute.
=> Refactor base.pp

manifests/component/action.pp, manifests/component/global_config.pp, manifests/component/input.pp, manifests/component/legacy_config.pp, manifests/component/lookup_table.pp, manifests/component/module.pp, manifests/component/parser.pp, manifests/component/ruleset.pp, manifests/component/template.pp
=> puppet-lint: Fix optional_default violations

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, Dockerfile, Gemfile, spec/acceptance/base_spec.rb, spec/classes/init_spec.rb, spec/setup_acceptance_node.pp, spec/spec_helper_acceptance.rb
=> modulesync 5.3.0

CHANGELOG.md, REFERENCE.md, metadata.json
=> release 6.0.0

.msync.yml, Gemfile, manifests/config/global.pp
=> modulesync 5.4.0

manifests/config/global.pp, metadata.json, templates/action.epp
This PR also include:
* #215
* #216
=> Drop Debian 9 / Ubuntu 16.04 (EOL)

.github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, .pmtignore, Gemfile, spec/defines/generate_concat_spec.rb
=> modulesync 7.2.0

spec/defines/component/global_config_spec.rb, spec/defines/component/input_spec.rb, spec/defines/component/legacy_config_spec.rb, spec/defines/component/main_queue_spec.rb, spec/defines/component/module_spec.rb, spec/defines/component/parser_spec.rb, spec/defines/component/ruleset_spec.rb, spec/defines/component/template_spec.rb, templates/template.epp
Update code so that the list_description parentheses are closed correctly
Fixes #252
=> templates/template.epp:correct formating

metadata.json
=> allow puppetlabs/apt 10.x
