CONTRIBUTORS.md, README.md, data/common.yaml, manifests/client.pp, manifests/component/legacy_config.pp, manifests/config.pp, manifests/config/legacy.pp, manifests/init.pp, manifests/server.pp, templates/legacy_config.epp
The documentation needs to be updated pending your approval. I've tested it with the below data. If you have any suggestions for improvement, I'm happy to implement it. thanks.
This time I will do the documentation as a separate pull request :)
```
rsyslog::client::legacy_config:
auth_priv_rule:
key: "auth,authpriv.*"
value: "/var/log/auth.log"
auth_none_rule:
key: "*.*;auth,authpriv.none"
value: "/var/log/syslog"
syslog_all_rule:
key: "syslog.*"
value: "/var/log/rsyslog.log"
kernel_all_rule:
key: "kern.*"
value: "/var/log/kern.log"
mail_all_rule:
key: "mail.*"
value: "/var/log/mail.log"
mail_error_rule:
key: "mail.err"
value: "/var/log/mail.err"
news_critical_rule:
key: "news.crit"
value: "/var/log/news/news.crit"
news_error_rule:
key: "news.err"
value: "/var/log/news/news.err" …
```
=> Added support for legacy options in the module

manifests/component/action.pp, spec/defines/component/action_spec.rb, templates/action.epp
Provides optional logger facility to action component. default action doesnt expect facility to be declaerd. rspec tests has been updated for the action component to support the new features.
````
rsyslog::server::actions:
all_logs:
type: omfile
facility: "*.*;auth,authpriv.none"
config:
dynaFile: "remoteSyslog"
specifics: "/var/log/test"
kern_logs:
type: omfile
facility: "kern.*"
config:
dynaFile: "remoteSyslog"
file: "/var/log/kern.log"
cmd: "/proc/cmdline"
elasticsearch:
type: omelasticsearch
config:
template: "plain-syslog"
searchIndex: "logstash-index"
queue.type: "linkedlist"
queue.spoolDirectory: "/var/log/rsyslog/queue"
queue.filename: "dbq"
queue.maxdiskspace: "100g"
queue.maxfilesize: "100m"
queue.SaveOnShutdown: "on"
server: "10.8.200.38"
action.resumeretrycount: "-1"
bulkmode: …
```
=> Updated the action component to support logger facility

spec/classes/config/main_queue_spec.rb, spec/classes/config/modules_spec.rb, spec/classes/init_spec.rb, spec/defines/component/action_spec.rb, spec/defines/component/global_config_spec.rb, spec/defines/component/input_spec.rb, spec/defines/component/legacy_config_spec.rb, spec/defines/component/module_spec.rb, spec/defines/component/template_spec.rb, spec/spec_helper.rb, templates/global_config.epp
Since fixing the previous problem where a misaligment of the use of PUPPET_VERSION and PUPPET_GEM_VERSION meant the tests werent actually getting run against the right puppet versions.  That fix exposed the issue that data in modules was released in 4.3.0 and the rspec tests were requiring that rsyslog defaults get looked up magically.  This PR fixes the tests for puppet < 4.3 by explicitly declaring the class.
=> fixes to rspec

.travis.yml, README.md, data/common.yaml, manifests/generate_concat.pp, manifests/init.pp
Added an `external_service` boolean parameter for allowing puppet-rsyslog to manage configs/logs shared with other processes that may be managed by other modules.
The most common example would be if someone is using `garethr-docker` to create and manage an rsyslog docker container and `crayfishx-rsyslog` to manage configuration that is shared with the container via a volume. 
In this example, `garethr-docker` generates a service file (upstart, init.d, or systemd) that will stop/start the container as though it were a service. As rsyslog requires a stop/start to read configuration changes, allowing this module to set an externally managed service that `crayfishx-rsyslog` can notify on configuration changes is not only extremely helpful, but almost required.
`external_service` is a boolean …
=> Create `external_service` parameter

.sync.yml, .travis.yml, metadata.json, spec/acceptance/ruleset_spec.rb, spec/defines/component/expression_filter_spec.rb, spec/defines/component/ruleset_spec.rb, spec/spec_helper_acceptance.rb, templates/expression_filter.epp, templates/ruleset.epp, templates/tasks.epp
The Ruleset EPP template has been refactored for readability and
reduced duplication. The template now calls other templates to fill
out its configuration data for all values except the global ruleset
stop option.
closes #32, #41, and #42
=> Refactor rulesets

README.md, manifests/generate_concat.pp, spec/acceptance/inputs_spec.rb
Correctly addresses bug in #45 
This sets the concat ordering functionality to order `numerically` as that matches the original design of this module.
=> Set concat order numeric

CHANGELOG.md, manifests/component/property_filter.pp, metadata.json
Add additional valid property filter operators
The property filter $operators parameter was missing two valid operators in the Enum data type - startswith_i and contains_i.
=> Property filter operators

.travis.yml
Due to an issue with the current release of [Travis-CI/DPL](https://github.com/travis-ci/dpl) that is missing the `json-pure` gem from the Puppet Forge release process. 
This is the suggested workaround until the issue is fixed in DPL since we can't afford to halt releases waiting for Travis-CI
=> Test travis release fix

README.md, manifests/component/property_filter.pp, spec/acceptance/expression_filter_spec.rb, spec/acceptance/ruleset_spec.rb, spec/defines/component/expression_filter_spec.rb, spec/defines/component/property_filter_spec.rb, spec/defines/component/ruleset_spec.rb, templates/expression_filter.epp, templates/property_filter.epp, templates/tasks.epp
A Hash cannot contain two identical keys and since Rsyslog can have the same config option repeated, the task parameter related to filters needed to be updated to be an Array rather than a Hash.
=> Switch datatype from Hash to array fo task param

README.md, spec/defines/component/ruleset_spec.rb, templates/exec.epp, templates/tasks.epp
This PR adds a new task to the rulesets which allows the usage of the 'execute program' feature.
Fixes #80
=> Add Feature: Allow 'execute program' (^) as a task in in rulesets

.fixtures.yml, .sync.yml, .travis.yml, data/common.yaml, hiera.yaml, manifests/base.pp, manifests/init.pp, manifests/server.pp, metadata.json, spec/acceptance/actions_spec.rb, spec/acceptance/base_spec.rb, spec/acceptance/inputs_spec.rb, spec/acceptance/rsyslog_spec.rb, spec/acceptance/ruleset_spec.rb, spec/classes/init_spec.rb, spec/spec_helper_acceptance.rb
* Added support to use the upstream Adiscon Rsyslog repos maintained by Rsyslog for Ubuntu and EL.
* Unfortunately, Rsyslog doesn't support other distros, so those distros will continue to use the system packages for the time being.
* Fixed several acceptance tests.
* Removed Ubuntu 14.04 from the travis matrix
* Removed support for EL 6. Due to dependency issues with EL6 and rsyslog, it is difficult to test. We cannot support OSes we can't test.
* Added Ubuntu 18.04  to the Matrix.
* Add Dependent modules for repo management support
=> Add support to use upstream repos in Ubuntu and EL

types/modules/input.pp, types/modules/message.pp, types/modules/parser.pp, types/modules/string.pp
Add remaining built-in rsyslog module types. These will be used and tested in the specific parameters for configuring module config and module calls. These are not to be confused with puppet modules.
=> Add remaining rsyslog module types

templates/modules.epp
There are rsyslog config values that accepts an array instead of
string[1]. In such cases the template generated will have a corrupted
output like
key = "[value1, value2]"
instead of
key = ["value1", "value2"]
This fixes template output by passing value to to_json{} in stdlib,
which generates valid output in case of an array.
[1] https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html#permittedpeer
=> Fix template output if value is array

manifests/base.pp
Text files should end with a newline.
=> base.pp: add final newline to rsyslog.conf

README.md, metadata.json
Add support for EL8 distributions using the system rsyslog package (8.37). The upstream repo is currently broken for EL8 and has a guard clause in it. This does not include acceptance tests yet either.
=> Add EL 8 support

manifests/base.pp
This file could be created before packages installation. This commit
forces the configuration of the file after the package installation.
When the file is created empty before package installation, then this action could fail with errors like
```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install rsyslog' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
liblognorm5
Suggested packages:
rsyslog-mysql | rsyslog-pgsql rsyslog-doc rsyslog-relp rsyslog-elasticsearch
rsyslog-mmjsonparse rsyslog-imptcp rsyslog-gnutls rsyslog-openssl
rsyslog-udpspoof rsyslog-mmrm1stspace rsyslog-mmutf8fix rsyslog-kafka
rsyslog-omstdout
The following NEW packages will be installed: …
```
=> Configure /etc/rsyslog.conf after package installation

templates/input.epp
This PR permits an option in an input to be an array.
For example, according to [imkafka documentation](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imkafka.html) when you have more than just one broker configuration is like this:
```
input(type="imkafka" topic="mytopic"
broker=["localhost:9092",
"localhost:9093",
"localhost:9094"]
)
```
but a code like:
```
rsyslog::config::inputs:
imkafka:
type: imkafka
config:
topic: mytopic
consumergroup: mygroup
broker:
- localhost:9092
- localhost:9093
- localhost:9094
```
creates the config:
```
input(type="imkafka"
topic="mytopic"
broker="[localhost:9092, localhost:9093, localhost:9094]"
consumergroup="mygroup"
)
```
This patch lets options in `config` hash to be an array and be treated like an array
=> Let config values be an array in inputs

README.md, manifests/component/expression_filter.pp, templates/expression_filter.epp, templates/ruleset.epp
Fixes an issue with the expression filter template where all `else if` keys would be treated as the same key (as YAML does). Added new documentation and template logic that now looks for user-defined keys that are descriptive to the check, with the exception of the first condition and the last condition, which have specific keywords assigned to them:
First Condition (required):
* `if` - for backwards compatibility
* `main` - Descriptive as the main condition of the filter.
* Required and must use one of the keywords in the YAML or Puppet code.
Last Condition:
* `else` - for backwards compatibility
* `default` - Descriptive as the "default" or "fall through" condition of the filter.
* Required if more than one condition is defined.
Fixed #164
=> Fix issues with the expression filter keys

manifests/component/custom_config.pp
This change gives rsyslog::component::custom_config some parameter defaults, so that it can be used (almost) as easy as rsyslog::snippet from saz/rsyslog:
```
rsyslog::component::custom_config {
'foobar':
content => 'if $programname == "foobar" then stop';
}
```
creates `/etc/rsyslog.d/foobar.conf` with this content.
Fixes #109
=> add parameter defaults to rsyslog::component::custom_config

manifests/base.pp, spec/classes/init_spec.rb
Ensures rsyslog service is restarted if the rsyslog confdir is purged.
Fixes #172
=> Add service restart to rsyslog confdir file resource

spec/classes/init_spec.rb
The os.family fact retuns 'Debian' in Ubuntu systems. We should use
the os.name fact to distinguish Ubuntu from the other Debian families.
N/A
=> Fix wrong condition to detect Ubuntu

manifests/base.pp, metadata.json, spec/acceptance/base_spec.rb, spec/classes/init_spec.rb, spec/spec_helper_acceptance.rb
This change adds CentOS Stream 9 (aka CentOS 9) to supported operating
systems.
N/A
=> Add CentOS 9 to supported operating systems

README.md
The `rsyslog::config::inputs` section of the README had a typo in its puppet example. The Hiera example is already correct.
In the _will produce_ part, a comment was missing.
n/a
=> Fix typo for `inputs` example in README

README.md
The `rsyslog::config::rulesets` section of the README has a typo in its example with a lookup table (both in puppet and hiera example).
The `lookup_file` and `reload_on_hup` parameters should not be in the `lookup_json` hash, but directly in the hash of the table.
Note that examples in section `rsyslog::config::lookup_tables` are already correct.
n/a
=> Fix lookup_tables typo in readme examples

manifests/config/global.pp
The ! has higher precedence than the `in` operator.
Fixes #223.
=> Fix `global_config` rendering

spec/acceptance/base_spec.rb, spec/acceptance/rsyslog_spec.rb
OracleLinux is a RedHat derivative. It was added to the test matrix but we are missing some conditions in the tests.
=> Fix CI on OracleLinux

CONTRIBUTORS.md, README.md
Since version v5.0.0 the client / server model is removed from the module but there are still some references in the README.md that can lead to a misunderstanding of how to use that module.
This PR fixes these references with the replacements that had been added for the client / server namespace classes.
Closes #206
=> Fix old client/server model reference in README

metadata.json, spec/acceptance/actions_spec.rb
Fedora 32 went EOL long ago. Fedora 37 is EOL in three months, so might as well only list Fedora 38 at this point.
=> Update supported Fedora version to 38

metadata.json
This is a `bug` instead of a breaking change as sl8 never existed and no supported platform is being removed. This is fixing a bug with the module's metadata.
=> drop support for scientific linux 8 -- sl8 never existed

spec/acceptance/actions_spec.rb
=> fix f38 acceptance tests failing on rsyslog-elasticsearch

manifests/base.pp
Makes use of advanced/rainerscript format in base.pp to replace the legacy IncludeConfig statement.
=> base: rainerscript replacement for `$IncludeConfig`

manifests/base.pp
Hello, I would like to send the PR
When $rsyslog::config_file changes, the rsyslog service doesn't restart. The PR fixes it, adding a notification.
=> Notify the service when there is a change in the config_file

README.md, REFERENCE.md, manifests/config.pp
Fixes this kind of error:
```
Syntax error at 'global_config' (file: /etc/puppetlabs/code/environments/rsyslog/site/profile/manifests/rsyslog.pp, line: 5, column: 5)
1  # Class: profile::rsyslog
2  # By default provides client configuration, can optionally provide server configuration
3  class profile::rsyslog {
4    class { 'rsyslog::config':
5      'global_config' => {}
[...]
```
Also in this commit a minor typofix in REFERENCE.
=> README: puppet refuses to parse class attributes as strings

REFERENCE.md, manifests/base.pp, manifests/init.pp
- Puppet:  puppet-agent-7.33.0-1.el7.x86_64
- Distribution:   Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Module version:  [Commit 40440a8](https://github.com/voxpupuli/puppet-rsyslog/commit/40440a8adf609d824402dba2bcf4811b61e648c4)
The module incorrectly assumes that the [include()](https://www.rsyslog.com/doc/rainerscript/include.html) object is supported on rsyslog without first checking (or providing an override) for an appropriate version of rsyslog.
This module uses the new syntax of `include()` instead of the older `$IncludeConfig`.  The include() syntax is supported only on [rsyslog > 8.33.0](https://www.rsyslog.com/doc/rainerscript/include.html).
```
syslogd[39175]: action 'include' treated as ':omusrmsg:include' - please use ':omusrmsg:include' syntax instead, …
```
=> Allow overriding of the `Include` directive in the `/etc/rsyslog.conf` file to support older versions of `rsyslogd`
